/* Sample payloads for reviewing the interface without a bench.

   These are not invented numbers. The verdicts are the output of running the
   real engine over real ERPNext rows for 6 Jul – 2 Aug 2026, so the layout is
   being judged against the shape of data it will actually receive.

   The connection rows are honest too: four adapters are written, five are not,
   and none of them has pulled a row on this laptop. */

export const SAMPLE = {
  integrity: {
    checked_at: "2026-08-03 09:00:00",
    syncs: [
      { source: "erpnext", run_day: "2026-08-03", ok: 1, rows_written: 2417, duration_ms: 4180 },
    ],
    anomalies: [
      { metric: "items_per_order", day: "2026-07-28", ratio: 1.49, baseline: 1.84, deviation_pct: -19.0 },
    ],
    freshness: [{ source: "erpnext", latest: "2026-08-03" }],
  },

  connections: [
    { source: "erpnext", label: "ERPNext", timezone: "Europe/Istanbul", maturity_hours: 6,
      covers: "Orders, delivery outcomes, revenue", credential_key: null,
      implemented: true, configured: true, enabled: true, healthy: true,
      last_ok: "2026-08-03", last_rows: 2417, consecutive_failures: 0, account_id: null, last_error: null },
    { source: "meta", label: "Meta Ads", timezone: "Africa/Casablanca", maturity_hours: 24,
      covers: "Spend, creative, pixel events", credential_key: "meta_access_token",
      implemented: true, configured: true, enabled: false, healthy: false,
      last_ok: null, last_rows: 0, consecutive_failures: 0, account_id: null, last_error: null },
    { source: "google_ads", label: "Google Ads", timezone: "Europe/Istanbul", maturity_hours: 72,
      covers: "Spend, PMAX value, conversion actions", credential_key: "google_ads_refresh_token",
      implemented: true, configured: true, enabled: false, healthy: false,
      last_ok: null, last_rows: 0, consecutive_failures: 0, account_id: null, last_error: null },
    { source: "tiktok", label: "TikTok Ads", timezone: "Europe/Istanbul", maturity_hours: 48,
      covers: "Spend, creative, changelog", credential_key: "tiktok_access_token",
      implemented: true, configured: true, enabled: false, healthy: false,
      last_ok: null, last_rows: 0, consecutive_failures: 0, account_id: null, last_error: null },
    { source: "shopify", label: "Shopify", timezone: "Africa/Casablanca", maturity_hours: 12,
      covers: "Sessions, add-to-cart, checkout", credential_key: "shopify_access_token",
      implemented: false, configured: true, enabled: false, healthy: false,
      last_ok: null, last_rows: 0, consecutive_failures: 0, account_id: null, last_error: null },
    { source: "ga4", label: "Google Analytics 4", timezone: "Africa/Casablanca", maturity_hours: 48,
      covers: "Landing-page CVR, channel mix", credential_key: "ga4_credentials",
      implemented: false, configured: false, enabled: false, healthy: false,
      last_ok: null, last_rows: 0, consecutive_failures: 0, account_id: null, last_error: null },
    { source: "clarity", label: "Microsoft Clarity", timezone: "UTC", maturity_hours: 24,
      covers: "Rage clicks, dead clicks, scroll depth", credential_key: "clarity_api_token",
      implemented: false, configured: true, enabled: false, healthy: false,
      last_ok: null, last_rows: 0, consecutive_failures: 0, account_id: null, last_error: null },
    { source: "semrush", label: "SEMrush", timezone: "UTC", maturity_hours: 168,
      covers: "Positions, organic traffic", credential_key: "semrush_api_key",
      implemented: false, configured: true, enabled: false, healthy: false,
      last_ok: null, last_rows: 0, consecutive_failures: 0, account_id: null, last_error: null },
    { source: "appsflyer", label: "AppsFlyer", timezone: "UTC", maturity_hours: 48,
      covers: "Installs, in-app events, mobile ROAS", credential_key: "appsflyer_api_token",
      implemented: false, configured: true, enabled: false, healthy: false,
      last_ok: null, last_rows: 0, consecutive_failures: 0, account_id: null, last_error: null },
  ],

  settings: {
    alert_email: "ahmedbadran2017@gmail.com",
    whatsapp_to: "",
    whatsapp_webhook: false,
    whatsapp_min_severity: "High",
    window_days: 28,
    judge_hour: 9,
    agent_enabled: true,
    agent_effort: "high",
    agent_model: "claude-opus-5",
    agent_can_execute: false,
    api_key_configured: false,
  },

  rules: [
    {
      name: null, entity_type: "Product", metric: "delivery_rate", source: "erpnext",
      enabled: 1, higher_is_better: 1, min_sample: 60, min_weight: 5000, min_days: 14,
      gap_act: 8, gap_material: 3, impact_floor: 5000, kill_at: 60, dormant_after_days: null,
    },
  ],

  overview: {
    today: { orders: 284, revenue_mad: 58420, confirmed: 231, confirmation_pct: 81.3, ad_spend_try: 3066 },
    month: {
      orders: 8818, revenue_mad: 1821527, confirmed: 7131, confirmation_pct: 80.9,
      resolved: 6402, delivered: 5229, delivery_pct: 81.7, in_transit: 2416,
    },
    spend: {
      by_source: [], total_try: 0, total_mad: null,
      try_to_mad_rate: null, sources_reporting: 0,
    },
    blended: { cost_per_order_try: null, cost_per_delivered_try: null,
               note: "spend ÷ all orders, across every platform — not attributed" },
    as_of: "2026-08-03 09:00:00",
  },

  daily: Array.from({ length: 30 }, (_, i) => ({
    day: `2026-07-${String(i + 5).padStart(2, "0")}`,
    orders: [268,291,305,277,312,298,264,281,309,322,287,275,299,318,301,
             264,289,313,295,271,286,308,324,299,277,292,311,286,270,284][i],
    revenue_mad: [55e3,60e3,63e3,57e3,64e3,61e3,54e3,58e3,64e3,66e3,59e3,57e3,
                  62e3,66e3,62e3,54e3,60e3,65e3,61e3,56e3,59e3,63e3,67e3,62e3,
                  57e3,60e3,64e3,59e3,56e3,58420][i],
    confirmation_pct: [81.1,82.4,80.2,79.8,83.1,81.7,80.4,82.0,81.2,80.9,82.3,
                       79.6,81.5,82.8,80.7,79.9,81.8,82.2,80.5,81.0,82.6,81.4,
                       80.8,82.1,81.6,80.3,81.9,82.5,80.6,81.3][i],
    ad_spend_try: 0,
  })),

  suppliers: {
    window_days: 30, denominator_source: "erpnext",
    share_basis: "revenue of the suppliers listed",
    rows: [
      { supplier: "JHome", orders: 3860, skus: 184, revenue_mad: 712062, share_pct: 41.6, confirmation_pct: 87.8, delivery_pct: 84.1, aov_mad: 184 },
      { supplier: "MU Group", orders: 1897, skus: 532, revenue_mad: 333009, share_pct: 19.46, confirmation_pct: 75.3, delivery_pct: 79.2, aov_mad: 176 },
      { supplier: "Justyol", orders: 1415, skus: 114, revenue_mad: 275419, share_pct: 16.09, confirmation_pct: 83.2, delivery_pct: 82.6, aov_mad: 195 },
      { supplier: "Christelle Paris", orders: 678, skus: 47, revenue_mad: 84417, share_pct: 4.93, confirmation_pct: 80.7, delivery_pct: 80.1, aov_mad: 125 },
      { supplier: "Beauty Mall", orders: 130, skus: 112, revenue_mad: 34263, share_pct: 2.0, confirmation_pct: 51.7, delivery_pct: 68.4, aov_mad: 264 },
      { supplier: "Digitronics", orders: 25, skus: 13, revenue_mad: 34087, share_pct: 1.99, confirmation_pct: 16.0, delivery_pct: null, aov_mad: 1363 },
      { supplier: "Kitchen Life", orders: 128, skus: 46, revenue_mad: 27505, share_pct: 1.61, confirmation_pct: 81.6, delivery_pct: 83.0, aov_mad: 215 },
      { supplier: "TOMMYLIFE", orders: 110, skus: 136, revenue_mad: 24569, share_pct: 1.44, confirmation_pct: 70.3, delivery_pct: 74.9, aov_mad: 223 },
      { supplier: "Town Team", orders: 114, skus: 112, revenue_mad: 24457, share_pct: 1.43, confirmation_pct: 77.1, delivery_pct: 78.8, aov_mad: 215 },
      { supplier: "Maison good and well", orders: 51, skus: 33, revenue_mad: 21765, share_pct: 1.27, confirmation_pct: 69.6, delivery_pct: 72.0, aov_mad: 427 },
    ],
  },

  products: {
    window_days: 30, denominator_source: "erpnext", supplier: null,
    rows: [
      { item_code: "45862527402238", label: "Set de 12 bocaux carrés de conservation 1700 ml - STD", supplier: "JHome", orders: 782, qty: 812, revenue_mad: 184338, share_pct: 22.4, confirmation_pct: 88.1 },
      { item_code: "45779757236478", label: "12 Li Standlı Kendinden Yapışkanlı Kapaklı Kaşıklı Baharatlık Takımı - Gray", supplier: "MU Group", orders: 969, qty: 1004, revenue_mad: 144829, share_pct: 17.6, confirmation_pct: 74.2 },
      { item_code: "45820014362878", label: "Set de 4 boîtes de rangement carrées 6 L pour farine et légumineuses - STD", supplier: "JHome", orders: 642, qty: 668, revenue_mad: 144571, share_pct: 17.6, confirmation_pct: 86.4 },
      { item_code: "45779760283902", label: "Set de 12 pots à épices anthracite 555 ml avec étiquettes - STD", supplier: "JHome", orders: 651, qty: 679, revenue_mad: 139985, share_pct: 17.0, confirmation_pct: 85.9 },
      { item_code: "45779741180158", label: "Set de 12 contenants carrés 1205 ml noirs avec étiquettes - STD", supplier: "JHome", orders: 686, qty: 712, revenue_mad: 137175, share_pct: 16.7, confirmation_pct: 87.2 },
      { item_code: "45779739738366", label: "Set de 2 bouteilles d'huile en verre 750 ml avec support en bois - STD", supplier: "Justyol", orders: 306, qty: 318, revenue_mad: 59782, share_pct: 7.3, confirmation_pct: 83.6 },
      { item_code: "9135229141246", label: "Set de rangement cuisine - STD", supplier: "Justyol", orders: 178, qty: 184, revenue_mad: 21475, share_pct: 2.6, confirmation_pct: 80.4 },
    ],
  },

  buyers: {
    window_days: 30, unmapped_accounts: 0, rows: [],
    note: "Platform-reported ROAS, per platform. Buyers run different accounts and products — this is not a ranking.",
  },
  buyerActivity: { window_days: 30, summary: [], recent: [], coverage: [] },

  capacity: {
    window_days: 14,
    totals: { spend: 21461, authorised: 194670, utilization: 11.0 },
    budget_capped: 0, delivery_limited: 6, no_budget_data: 0,
    headline:
      "6 campaign(s) below 40% of budget — raising these does nothing, the constraint is delivery: App Install | Android | 20, JHome | PMAX | Morocco, PMAX | Fashion & Accessor",
    rows: [
      { entity_id: "google:23776204545", label: "App Install | Android | 2026-04 (new version)", platform: "google_ads",
        spend: 11185, spend_per_day: 1598, budget: 15000, budget_type: "daily", utilization: 10.7,
        unused: 93814, roas: 1.36, orders: 13, delivery_status: "ELIGIBLE", constraint: "delivery", active_days: 7, last_day: "2026-08-02" },
      { entity_id: "google:23725632206", label: "JHome | PMAX | Morocco", platform: "google_ads",
        spend: 4523, spend_per_day: 646, budget: 8800, budget_type: "daily", utilization: 7.3,
        unused: 57077, roas: 8.2, orders: 31, delivery_status: "ELIGIBLE", constraint: "delivery", active_days: 7, last_day: "2026-08-02" },
      { entity_id: "google:24081372659", label: "PMAX | Fashion & Accessories | MA", platform: "google_ads",
        spend: 1785, spend_per_day: 255, budget: 640, budget_type: "daily", utilization: 39.8,
        unused: 2695, roas: 0.77, orders: 1, delivery_status: "ELIGIBLE", constraint: "delivery", active_days: 7, last_day: "2026-08-02" },
      { entity_id: "google:22536302088", label: "ES | Branded Search | Max Value", platform: "google_ads",
        spend: 1553, spend_per_day: 222, budget: 2000, budget_type: "daily", utilization: 11.1,
        unused: 12447, roas: 14.9, orders: 19, delivery_status: "ELIGIBLE", constraint: "delivery", active_days: 7, last_day: "2026-08-02" },
      { entity_id: "google:24076392624", label: "PMAX | Beauty & Perfumes | MA", platform: "google_ads",
        spend: 1525, spend_per_day: 218, budget: 730, budget_type: "daily", utilization: 29.9,
        unused: 3585, roas: 0.55, orders: 1, delivery_status: "ELIGIBLE", constraint: "delivery", active_days: 7, last_day: "2026-08-02" },
      { entity_id: "google:24081372869", label: "PMAX | Rest of Catalog | MA", platform: "google_ads",
        spend: 890, spend_per_day: 127, budget: 640, budget_type: "daily", utilization: 19.9,
        unused: 3590, roas: 0.0, orders: 0, delivery_status: "ELIGIBLE", constraint: "delivery", active_days: 7, last_day: "2026-08-02" },
    ],
  },

  alerts: [],
  agentRuns: [],

  verdicts: [
    {
      name: "V-0001",
      entity_type: "Product",
      entity_id: "45779757236478",
      entity_label: "12 Li Standlı Kendinden Yapışkanlı Kapaklı Kaşıklı Baharatlık Takımı - Gray",
      verdict: "Fix",
      metric: "delivery_rate",
      impact_mad: 8827,
      headline: "77.5 vs 81.7 baseline",
      recommended_action: "A 4.2 point gap on 895 orders costs ~8,827 MAD/month",
      numerator: 694,
      denominator: 895,
      denominator_source: "erpnext",
      window_start: "2026-07-06",
      window_end: "2026-08-02",
      sample_size: 895,
      query_ref:
        "growth_portal.analyzers.product.ProductAnalyzer.collect — latest Shipment Tracking row per sales_order, joined to Sales Order Item, grouped on item_code, rates over resolved orders only",
      evidence: {
        value: 77.54,
        baseline: 81.67,
        dominant_failure: "Confirmation",
        refused_product: 8,
        unreachable: 67,
        cancelled_confirm: 75,
        duplicate_or_denied: 21,
        orders_placed: 969,
      },
    },
    {
      name: "V-0002",
      entity_type: "Product",
      entity_id: "45779740033278",
      entity_label: "Set de 3 passoires métalliques avec crochets pour casseroles - STD",
      verdict: "Watch",
      metric: "delivery_rate",
      impact_mad: 0,
      headline: "Sample 13 — below the minimum of 60",
      recommended_action: "Wait for a longer window before judging",
      numerator: 9,
      denominator: 13,
      denominator_source: "erpnext",
      window_start: "2026-07-06",
      window_end: "2026-08-02",
      sample_size: 13,
      query_ref: "growth_portal.analyzers.product.ProductAnalyzer.collect",
      evidence: { value: 69.2, baseline: 81.67 },
    },
    {
      name: "V-0003",
      entity_type: "Campaign",
      entity_id: "tiktok:1870866421172754",
      entity_label: "UGC-DPA-All-Campaign",
      verdict: "Grow",
      metric: "roas",
      impact_mad: 11400,
      headline: "15.90 — 4.20 points above baseline",
      recommended_action: "The same spend buys a better result here — a candidate to scale",
      numerator: 31020,
      denominator: 1951,
      denominator_source: "tiktok",
      window_start: "2026-07-06",
      window_end: "2026-08-02",
      sample_size: 25,
      query_ref:
        "growth_portal.analyzers.campaign.CampaignAnalyzer.collect — Entity Metric where source=tiktok, summed per campaign over the window; value = platform-reported revenue ÷ platform-reported spend, both from tiktok",
      evidence: {
        value: 15.9, baseline: 11.7, platform: "tiktok", currency: "TRY",
        cpa: 78, cpm: 19.4, orders: 25, provisional_days: 2,
        revenue_basis: "count_x_value",
        series: [9.1, 10.4, 12.8, 11.2, 14.6, 13.9, 16.2, 15.1, 17.8, 15.9],
      },
    },
    {
      name: "V-0004",
      entity_type: "Campaign",
      entity_id: "google:23776204545",
      entity_label: "App Install | Android | 2026-04 (new version)",
      verdict: "Kill",
      metric: "roas",
      impact_mad: 9640,
      headline: "0.20 — below the viability floor of 1.5",
      recommended_action: "Stop the spend — the gap costs ~9,640 MAD/month",
      numerator: 2011,
      denominator: 9854,
      denominator_source: "google_ads",
      window_start: "2026-07-06",
      window_end: "2026-08-02",
      sample_size: 1681,
      query_ref:
        "growth_portal.analyzers.campaign.CampaignAnalyzer.collect — Entity Metric where source=google_ads, summed per campaign over the window; value = platform-reported revenue ÷ platform-reported spend, both from google_ads",
      evidence: {
        value: 0.2, baseline: 3.8, platform: "google_ads", currency: "TRY",
        cpa: 5.9, orders: 1681, provisional_days: 3,
        series: [0.4, 0.3, 0.35, 0.28, 0.22, 0.25, 0.19, 0.21, 0.2, 0.2],
      },
    },
  ],

  campaignVerdicts: [],

  findings: [
    {
      name: "F-0001",
      title:
        "The worst-delivering product is the only one still named in Turkish — 77.5% vs 81.7% baseline",
      severity: "High",
      status: "Open",
      entity_type: "Product",
      entity_id: "45779757236478",
      creation: "2026-08-03 09:04:00",
      body:
        "Among products above the weight floor, this is the only one still carrying its Turkish name while the rest were renamed to French. Its largest failure source is cancellation at confirmation or at the door (75 orders), not refusal of the product itself (8) — consistent with a customer who agrees on the phone and backs out on seeing the item. The number is a fact; the link to language is a hypothesis that needs a test: rename to French and measure the same rate over 14 days.",
      evidence: {
        numerator: 694,
        denominator: 895,
        denominator_source: "erpnext",
        window_start: "2026-07-06",
        window_end: "2026-08-02",
        query_ref: "growth_portal.analyzers.product.ProductAnalyzer.collect",
      },
    },
  ],

  entity: {
    entity: {
      entity_key: "45779757236478",
      entity_type: "Product",
      entity_label: "12 Li Standlı Kendinden Yapışkanlı Kapaklı Kaşıklı Baharatlık Takımı - Gray",
      source: "erpnext",
    },
    series: [],
    verdicts: [],
    changes: [],
  },
};
